#!/usr/bin/env python3
"""Generate web/data.js for the in-browser playground.

Pulls the calibrated bands + function-word vectors (corpus/), the AI-tell lexicon
(lexicons/), and the scoring CONSTANTS straight from scripts/stylo.py — so the
browser scorer can never drift from the canonical Python one. Re-run after any
recalibration:  python3 web/build_playground.py
"""
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT / "scripts"))
import stylo  # noqa: E402

REGISTERS = [
    "spontaneous", "literary", "journalism", "scientific",
    "business", "social-media", "technical-docs",
]


def main():
    registers = {}
    examples = {}
    for reg in REGISTERS:
        ref = json.loads((ROOT / "corpus" / reg / "reference-stats.json").read_text())
        registers[reg] = {
            "bands": ref.get("bands", {}),
            "fw": ref.get("function_word_vector", {}),
            "n_texts": ref.get("n_texts"),
            "calibrated": ref.get("calibrated", False),
        }
        # one short example per register (first AI sample), for the "load example" button
        samples = sorted((ROOT / "eval" / "ai_samples" / reg).glob("*.txt"))
        if samples:
            examples[reg] = samples[0].read_text(encoding="utf-8").strip()

    data = {
        "registers": registers,
        "examples": examples,
        "lexicon": json.loads((ROOT / "lexicons" / "ai_tells.json").read_text()),
        "constants": {
            "FUNCTION_WORDS": sorted(stylo.FUNCTION_WORDS),
            "OVER_CORRECTION": sorted(stylo.OVER_CORRECTION),
            "TELL_WEIGHT": stylo.TELL_WEIGHT,
            "SELF_TELL_WEIGHT": stylo.SELF_TELL_WEIGHT,
            "DISCOURSE_WEIGHT": stylo.DISCOURSE_WEIGHT,
            "DISCOURSE_KEYS": list(stylo.DISCOURSE_KEYS),
            "DEFAULT_DISCOURSE_BANDS": stylo.DEFAULT_DISCOURSE_BANDS,
            "TRANSITION_OPENERS": list(stylo.TRANSITION_OPENERS),
            "STRUCTURAL_OPENERS": list(stylo.STRUCTURAL_OPENERS),
        },
        "generated_from": "scripts/stylo.py + corpus/ + lexicons/ai_tells.json",
    }

    out = HERE / "data.js"
    out.write_text(
        "// AUTO-GENERATED by web/build_playground.py — do not edit by hand.\n"
        "// Bands, lexicon, and scoring constants mirror scripts/stylo.py exactly.\n"
        "globalThis.HP_DATA = " + json.dumps(data, ensure_ascii=False) + ";\n",
        encoding="utf-8",
    )
    kb = out.stat().st_size / 1024
    print(f"wrote {out.relative_to(ROOT)} ({kb:.0f} KB) — "
          f"{len(registers)} registers, {len(data['lexicon'])} tell entries")


if __name__ == "__main__":
    main()
